############################################################
# FIGURE GENERATION FOR FINGERPRINT TDA MANUSCRIPT
#
# Generates:
#   fig_pipeline.pdf  Pipeline illustration (binary → DT → PD → Betti)
#                    for both ridge and valley channels
#   fig_patches.pdf  Local patch visualization: 64 anchor locations
#                    on a fingerprint, plus three example patches with
#                    their persistence diagrams
#   fig_score_dists.pdf  Score distributions (TopoLR vs LPOT vs Fusion)
#
# The ROC curves figure is generated by fingerprintTDA.R.
#
# Usage: Rscript make_figures.R
############################################################

library(tidyverse)
library(EBImage)
library(TDA)

# ============================================================
# CONFIG
# ============================================================

output_dir <- "Outputs"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
dir.create("Manuscript", showWarnings = FALSE, recursive = TRUE)
binary_dir <- "Data/FVC2000_binary"
example_image <- file.path(binary_dir, "2_1_bin.png")

maxscale <- 20
target_size <- 150
n_betti_points <- 50

# ============================================================
# HELPER FUNCTIONS (from fingerprintTDA.R)
# ============================================================

read_binary_fingerprint <- function(path) {
  img <- EBImage::readImage(path)
  if (length(dim(img)) == 3) img <- EBImage::channel(img, "gray")
  mat <- as.matrix(img)
  mat[!is.finite(mat)] <- 0
  bin <- as.integer(mat >= 0.5)
  dim(bin) <- dim(mat)
  if (mean(bin) > 0.5) bin <- 1L - bin
  bin
}

compute_dt_to_ridge <- function(bin) {
  inv <- 1L - bin
  storage.mode(inv) <- "integer"
  as.matrix(EBImage::distmap(inv))
}

compute_dt_to_valley <- function(bin) {
  storage.mode(bin) <- "integer"
  as.matrix(EBImage::distmap(bin))
}

downsample_matrix <- function(mat, target_size) {
  nr <- nrow(mat); nc <- ncol(mat)
  if (nr <= target_size && nc <= target_size) return(mat)
  step <- max(ceiling(nr / target_size), ceiling(nc / target_size))
  mat[seq(1, nr, by = step), seq(1, nc, by = step), drop = FALSE]
}

compute_persistence <- function(filt_mat, maxdim = 1, maxscale = 20) {
  x <- pmin(pmax(filt_mat, 0), maxscale)
  x[!is.finite(x)] <- maxscale
  x <- round(x, 1)
  tryCatch({
    TDA::gridDiag(
      FUNvalues = x,
      maxdimension = maxdim,
      sublevel = TRUE,
      library = "GUDHI",
      printProgress = FALSE
    )$diagram
  }, error = function(e) NULL)
}

compute_betti_curve <- function(diag, hom_dim, n_points, maxscale) {
  curve <- rep(0, n_points)
  if (is.null(diag)) return(curve)
  mat <- as.matrix(diag)
  idx <- mat[, 1] == hom_dim & is.finite(mat[, 2]) & is.finite(mat[, 3])
  if (!any(idx)) return(curve)
  birth <- mat[idx, 2]
  death <- mat[idx, 3]
  t_seq <- seq(0, maxscale, length.out = n_points)
  alive <- outer(birth, t_seq, "<=") & outer(death, t_seq, ">")
  colSums(alive)
}

# ============================================================
# FIGURE 1: PIPELINE ILLUSTRATION (RIDGE + VALLEY CHANNELS)
# ============================================================

cat("Generating Figure 1: Pipeline illustration...\n")

bin <- read_binary_fingerprint(example_image)
dt_ridge  <- compute_dt_to_ridge(bin)
dt_valley <- compute_dt_to_valley(bin)

# Downsample for PH (same as main pipeline)
dt_ridge_ds  <- downsample_matrix(dt_ridge,  target_size)
dt_valley_ds <- downsample_matrix(dt_valley, target_size)

# Compute persistence on both channels
diag_ridge  <- compute_persistence(dt_ridge_ds,  maxdim = 1, maxscale = maxscale)
diag_valley <- compute_persistence(dt_valley_ds, maxdim = 1, maxscale = maxscale)

# Extract H1 birth/death pairs from a diagram
extract_h1 <- function(diag) {
  m <- as.matrix(diag)
  i <- m[, 1] == 1 & is.finite(m[, 2]) & is.finite(m[, 3])
  list(birth = m[i, 2], death = m[i, 3])
}
h1_r <- extract_h1(diag_ridge)
h1_v <- extract_h1(diag_valley)

# Compute Betti curves for both channels
betti_r <- compute_betti_curve(diag_ridge,  1, n_betti_points, maxscale)
betti_v <- compute_betti_curve(diag_valley, 1, n_betti_points, maxscale)
t_seq   <- seq(0, maxscale, length.out = n_betti_points)

# Common y-limit so the two Betti curves are visually comparable
betti_ymax <- max(c(betti_r, betti_v))

# Viridis-like palette for heatmaps
heat_cols <- colorRampPalette(c("#440154", "#31688E", "#35B779", "#FDE725"))(256)

# --- Create multi-panel figure: 2 rows x 4 cols, top-left = binary ---
# Row 1: (a) binary    (b) DT_ridge    (c) H1_ridge    (d) Betti_ridge
# Row 2: [blank]       (e) DT_valley   (f) H1_valley   (g) Betti_valley

pdf(file.path(output_dir, "fig_pipeline.pdf"), width = 10, height = 6.0)

layout(matrix(c(1, 2, 3, 4,
                0, 5, 6, 7), nrow = 2, byrow = TRUE),
       widths  = c(1, 1, 1.15, 1.15),
       heights = c(1, 1))

# (a) Binary fingerprint
par(mar = c(0.5, 0.3, 2.2, 0.3), mgp = c(2, 0.7, 0),
    cex.main = 1.4, cex.axis = 1.2, cex.lab = 1.3)
image(t(bin[nrow(bin):1, ]), col = c("black", "white"),
      axes = FALSE, asp = 1, main = expression("(A) Binary image"))

# (b) Ridge distance transform
par(mar = c(0.5, 0.3, 2.2, 0.3))
dt_ridge_clip <- pmin(dt_ridge, maxscale)
image(t(dt_ridge_clip[nrow(dt_ridge_clip):1, ]),
      col = heat_cols, axes = FALSE, asp = 1,
      main = expression("(B) " * DT[ridge]))

# (c) Ridge H1 persistence diagram
par(mar = c(3.5, 3.5, 2.2, 0.5))
plot(h1_r$birth, h1_r$death, pch = 16, cex = 1.0,
     col = adjustcolor("#0072B2", alpha.f = 0.6),
     xlim = c(0, maxscale), ylim = c(0, maxscale), asp = 1,
     xlab = "Birth", ylab = "Death",
     main = expression("(C) " * H[1] * " of " * DT[ridge]))
abline(0, 1, lty = 2, col = "grey50")

# (d) Ridge Betti curve
par(mar = c(3.5, 3.5, 2.2, 0.5))
plot(t_seq, betti_r, type = "l", lwd = 2, col = "#D55E00",
     xlim = c(0, maxscale), ylim = c(0, betti_ymax),
     xlab = "Filtration value t", ylab = expression(beta[1](t)),
     main = expression("(D) Betti curve, ridge"))

# (e) Valley distance transform
par(mar = c(0.5, 0.3, 2.2, 0.3))
dt_valley_clip <- pmin(dt_valley, maxscale)
image(t(dt_valley_clip[nrow(dt_valley_clip):1, ]),
      col = heat_cols, axes = FALSE, asp = 1,
      main = expression("(E) " * DT[valley]))

# (f) Valley H1 persistence diagram
par(mar = c(3.5, 3.5, 2.2, 0.5))
plot(h1_v$birth, h1_v$death, pch = 16, cex = 1.0,
     col = adjustcolor("#0072B2", alpha.f = 0.6),
     xlim = c(0, maxscale), ylim = c(0, maxscale), asp = 1,
     xlab = "Birth", ylab = "Death",
     main = expression("(F) " * H[1] * " of " * DT[valley]))
abline(0, 1, lty = 2, col = "grey50")

# (g) Valley Betti curve
par(mar = c(3.5, 3.5, 2.2, 0.5))
plot(t_seq, betti_v, type = "l", lwd = 2, col = "#D55E00",
     xlim = c(0, maxscale), ylim = c(0, betti_ymax),
     xlab = "Filtration value t", ylab = expression(beta[1](t)),
     main = expression("(G) Betti curve, valley"))

dev.off()
file.copy(file.path(output_dir, "fig_pipeline.pdf"),
          "Manuscript/fig_pipeline.pdf", overwrite = TRUE)
cat("  -> Outputs/fig_pipeline.pdf (copied to Manuscript/)\n")


# ============================================================
# FIGURE 2: LOCAL PATCH VISUALIZATION
# ============================================================

cat("Generating Figure 2: Local patch visualization...\n")

# Helpers matching fingerprintTDA.R
make_disk_mask <- function(r) {
  xs <- -r:r; ys <- -r:r
  grid <- expand.grid(x = xs, y = ys)
  matrix((grid$x^2 + grid$y^2) <= r^2,
         nrow = length(xs), byrow = FALSE)
}

extract_patch_with_mask <- function(mat, cx, cy, r, mask_full) {
  nr <- nrow(mat); nc <- ncol(mat)
  r1 <- max(1, cx - r); r2 <- min(nr, cx + r)
  c1 <- max(1, cy - r); c2 <- min(nc, cy + r)
  patch <- mat[r1:r2, c1:c2, drop = FALSE]
  mr1 <- 1 + (r1 - (cx - r))
  mr2 <- mr1 + (r2 - r1)
  mc1 <- 1 + (c1 - (cy - r))
  mc2 <- mc1 + (c2 - c1)
  mask <- mask_full[mr1:mr2, mc1:mc2, drop = FALSE]
  list(patch = patch, mask = mask)
}

sample_anchor_points <- function(bin_ds, n_anchors, seed) {
  set.seed(seed)
  idx <- which(bin_ds == 1L, arr.ind = TRUE)
  if (nrow(idx) == 0) return(matrix(numeric(0), ncol = 2))
  pick <- sample.int(nrow(idx), n_anchors,
                     replace = (nrow(idx) < n_anchors))
  idx[pick, , drop = FALSE]
}

seed_from_string <- function(s) {
  # Must match fingerprintTDA.R::seed_from_string so the figure uses the same
  # anchors as the analysis.
  h <- digest::digest(s, algo = "sha256", serialize = FALSE)
  as.integer((strtoi(substr(h, 1, 7), base = 16L) %% 2147483646L) + 1L)
}

# Configuration matching the main pipeline (§4.4, §5.4)
patch_radius     <- 12
n_anchors_patch  <- 64
patch_seed       <- seed_from_string(basename(example_image))

# Downsampled binary for anchor sampling (full-image basis)
bin_ds <- downsample_matrix(bin, target_size)
storage.mode(bin_ds) <- "integer"

anchors <- sample_anchor_points(bin_ds, n_anchors_patch, patch_seed)

disk_mask <- make_disk_mask(patch_radius)

# Extract all 64 ridge patches (with disk mask applied) and compute their PDs
patches_ridge <- vector("list", n_anchors_patch)
patches_diag  <- vector("list", n_anchors_patch)
patch_persistence <- numeric(n_anchors_patch)  # total H1 persistence per patch
for (k in seq_len(n_anchors_patch)) {
  cx <- anchors[k, 1]; cy <- anchors[k, 2]
  pr <- extract_patch_with_mask(dt_ridge_ds, cx, cy,
                                patch_radius, disk_mask)
  pm <- pr$patch
  pm[!pr$mask] <- maxscale  # disk-mask: outside-disk pixels → clamp value
  patches_ridge[[k]] <- pm
  d <- compute_persistence(pm, maxdim = 1, maxscale = maxscale)
  patches_diag[[k]] <- d
  if (!is.null(d)) {
    m <- as.matrix(d)
    i <- m[, 1] == 1 & is.finite(m[, 2]) & is.finite(m[, 3])
    if (any(i)) patch_persistence[k] <- sum(pmax(0, m[i, 3] - m[i, 2]))
  }
}

# Select three representative patches: rich (max persistence), medium (median),
# sparse (min, typically near-empty diagram)
ord <- order(patch_persistence, decreasing = TRUE)
sel_idx <- as.integer(c(
  rich   = ord[1],
  medium = ord[ceiling(length(ord) / 2)],
  sparse = ord[length(ord)]
))
sel_letters <- c("B", "C", "D")
sel_descs   <- c("rich", "medium", "sparse")

# --- Create figure ---

pdf(file.path(output_dir, "fig_patches.pdf"), width = 9.5, height = 5.2)

layout(matrix(c(1, 2, 3, 4,
                1, 5, 6, 7), nrow = 2, byrow = TRUE),
       widths = c(2, 1, 1, 1))

# (a) Fingerprint with 64 anchors overlaid; three selected anchors highlighted
par(mar = c(0.5, 0.3, 2.2, 0.3), mgp = c(2, 0.7, 0),
    cex.main = 1.2, cex.axis = 0.9, cex.lab = 1.0)
image(t(bin_ds[nrow(bin_ds):1, ]),
      col = c("black", "white"), axes = FALSE, asp = 1,
      main = "(A) 64 anchor locations")
# Overlay: anchors in matrix coords (row, col) → plot coords ([0,1] x [0,1])
nr_ds <- nrow(bin_ds); nc_ds <- ncol(bin_ds)
ax <- (anchors[, 2] - 0.5) / nc_ds
ay <- 1 - (anchors[, 1] - 0.5) / nr_ds
points(ax, ay, pch = 21, bg = "#D55E00", col = "white",
       cex = 0.9, lwd = 0.6)
# Highlight the three selected anchors with large white-filled circles
# (dark blue border, dark blue bold letter) for high-contrast labels
points(ax[sel_idx], ay[sel_idx],
       pch = 21, bg = "white", col = "#0072B2", cex = 3.5, lwd = 2.2)
text(ax[sel_idx], ay[sel_idx], labels = sel_letters,
     col = "#0072B2", cex = 1.4, font = 2)

# Top row, cols 2-4: the three patches with disk masks applied.
# For display, reconstruct each patch with the out-of-disk pixels set to NA so
# they render as background (white) rather than the bright clamp color, and
# scale the colormap to each patch's actual interior data range so the full
# viridis gradient is used.
for (j in seq_along(sel_idx)) {
  k <- sel_idx[j]
  cx <- anchors[k, 1]; cy <- anchors[k, 2]
  pr_disp <- extract_patch_with_mask(dt_ridge_ds, cx, cy,
                                     patch_radius, disk_mask)
  patch_display <- pr_disp$patch
  patch_display[!pr_disp$mask] <- NA
  zmax <- suppressWarnings(max(patch_display, na.rm = TRUE))
  if (!is.finite(zmax) || zmax <= 0) zmax <- 1
  par(mar = c(0.5, 0.3, 2.2, 0.3))
  image(t(patch_display[nrow(patch_display):1, ]),
        col = heat_cols, axes = FALSE, asp = 1,
        zlim = c(0, zmax),
        main = sprintf("(%s) %s patch", sel_letters[j], sel_descs[j]))
  # Thin grey ring marking the disk boundary
  symbols(0.5, 0.5, circles = 0.5, inches = FALSE, add = TRUE,
          fg = "grey50", lty = 1, lwd = 0.8)
}

# Bottom row, cols 2-4: persistence diagrams of the three patches
pd_letters <- c("E", "F", "G")
for (j in seq_along(sel_idx)) {
  k <- sel_idx[j]
  d <- patches_diag[[k]]
  par(mar = c(3.5, 3.5, 2.2, 0.5))
  plot(NA, NA, xlim = c(0, maxscale), ylim = c(0, maxscale), asp = 1,
       xlab = "Birth", ylab = "Death",
       main = bquote("(" * .(pd_letters[j]) * ") " * H[1] *
                     " of (" * .(sel_letters[j]) * ")"))
  abline(0, 1, lty = 2, col = "grey50")
  if (!is.null(d)) {
    m <- as.matrix(d)
    i <- m[, 1] == 1 & is.finite(m[, 2]) & is.finite(m[, 3])
    if (any(i)) {
      points(m[i, 2], m[i, 3], pch = 16, cex = 1.4,
             col = adjustcolor("#0072B2", alpha.f = 0.7))
    }
  }
}

dev.off()
file.copy(file.path(output_dir, "fig_patches.pdf"),
          "Manuscript/fig_patches.pdf", overwrite = TRUE)
cat("  -> Outputs/fig_patches.pdf (copied to Manuscript/)\n")


# ============================================================
# FIGURE 3: SCORE DISTRIBUTIONS (COMPLEMENTARITY)
# ============================================================

cat("Generating Figure 3: Score distributions...\n")

scores_file <- file.path(output_dir, "scores_raw.csv")
if (!file.exists(scores_file)) {
  cat("  WARNING: scores_raw.csv not found. Run fingerprintTDA.R first.\n")
  cat("  Skipping Figure 3.\n")
} else {
  scores <- read_csv(scores_file, show_col_types = FALSE)

  fig_methods <- c("V23_full", "OT", "Fusion")
  fig_labels <- c("V23_full" = "TopoLR", "OT" = "LPOT", "Fusion" = "Fusion")

  scores_fig <- scores %>%
    filter(method %in% fig_methods) %>%
    mutate(
      label = fig_labels[method],
      label = factor(label, levels = c("TopoLR", "LPOT", "Fusion")),
      pair_type = ifelse(y == 1, "Genuine", "Impostor")
    )

  # Compute impostor quantile thresholds (pooled across folds) at FAR=1e-3
  thresholds <- scores_fig %>%
    filter(pair_type == "Impostor") %>%
    group_by(label) %>%
    summarize(thr = quantile(score, probs = 0.999), .groups = "drop")

  pdf(file.path(output_dir, "fig_score_dists.pdf"), width = 6.151, height = 2.8)

  par(mfrow = c(1, 3), mar = c(4, 3.8, 2.2, 1.2), mgp = c(2.2, 0.6, 0), cex.main = 1.1, cex.axis = 0.9, cex.lab = 1.0)

  for (meth in c("TopoLR", "LPOT", "Fusion")) {
    sub <- scores_fig %>% filter(label == meth)
    gen <- sub$score[sub$pair_type == "Genuine"]
    imp <- sub$score[sub$pair_type == "Impostor"]
    thr <- thresholds$thr[thresholds$label == meth]

    # Compute density
    d_gen <- density(gen, n = 512, adjust = 1.2)
    d_imp <- density(imp, n = 512, adjust = 1.2)

    # Set x-limits: use data range but trim extreme outliers
    all_scores <- c(gen, imp)
    xlims <- quantile(all_scores, c(0.005, 0.995))
    # Ensure threshold is visible
    xlims[2] <- max(xlims[2], thr * 1.05)
    xlims <- xlims + c(-1, 1) * diff(xlims) * 0.05  # 5% padding
    # Trim left edge where density is negligible (3% of peak)
    ymax <- max(c(d_gen$y, d_imp$y))
    left_active <- min(
      d_gen$x[which(d_gen$y > ymax * 0.03)[1]],
      d_imp$x[which(d_imp$y > ymax * 0.03)[1]]
    )
    xlims[1] <- max(xlims[1], left_active - diff(c(left_active, xlims[2])) * 0.08)
    ylims <- c(0, max(c(d_gen$y, d_imp$y)) * 1.15)

    plot(d_imp$x, d_imp$y, type = "l", lwd = 2, col = "#E69F00",
         xlim = xlims, ylim = ylims,
         xlab = "Similarity score", ylab = "Density", main = meth)
    polygon(d_imp$x, d_imp$y, col = adjustcolor("#E69F00", 0.2), border = NA)
    lines(d_gen$x, d_gen$y, lwd = 2, col = "#0072B2")
    polygon(d_gen$x, d_gen$y, col = adjustcolor("#0072B2", 0.2), border = NA)

    # Threshold line
    abline(v = thr, lty = 2, lwd = 1.5, col = "grey30")
    text(thr, ylims[2] * 0.93, expression("FAR=" * 10^{-3}), cex = 0.80, pos = 2, col = "grey30")

    # Legend (only on first panel, placed low-left where curves are sparse)
    if (meth == "TopoLR") {
      legend(xlims[1] + diff(xlims) * 0.22, ylims[2] * 0.75,
             legend = c("Genuine", "Impostor"),
             col = c("#0072B2", "#E69F00"), lwd = 2, cex = 0.80, bty = "n")
    }
  }

  dev.off()
  # Copy PDF to manuscript directory for Overleaf
  file.copy(file.path(output_dir, "fig_score_dists.pdf"), "Manuscript/fig_score_dists.pdf", overwrite = TRUE)
  cat("  -> Outputs/fig_score_dists.pdf (copied to Manuscript/)\n")
}

cat("Done.\n")
